name: Deploy Specific Lambda Functions

on:
  push:
    paths:
      - "lambda/downloadHandler/**"
      - "lambda/uploadHandler/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Install zip utility
      - name: Install zip tool
        run: sudo apt-get install zip -y

      # Step 3: Determine which Lambda directory was changed
      - name: Identify changed directories
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^lambda/downloadHandler/"; then
            echo "downloadHandler=true" >> $GITHUB_ENV
          fi
          if git diff --name-only HEAD~1 HEAD | grep -q "^lambda/uploadHandler/"; then
            echo "uploadHandler=true" >> $GITHUB_ENV
          fi

      # Step 4: Configure AWS credentials using the official AWS action
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Step 5: Deploy downloadHandler if it changed
      - name: Deploy downloadHandler
        if: env.downloadHandler == 'true'
        run: |
          cd lambda/downloadHandler && zip -r ../downloadHandler.zip .
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:209479299089:function:downloadHandler \
            --zip-file fileb://downloadHandler.zip

      # Step 6: Deploy uploadHandler if it changed
      - name: Deploy uploadHandler
        if: env.uploadHandler == 'true'
        run: |
          cd lambda/uploadHandler && zip -r ../uploadHandler.zip .
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:209479299089:function:uploadHandler \
            --zip-file fileb://uploadHandler.zip
